services:
  build:
    image: maven:3.9.12-amazoncorretto-25-debian
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: mvn package

  test:
    image: maven:3.9.12-amazoncorretto-25-debian
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: mvn test

  deploy:
    image: maven:3.9.22-amazoncorretto-25-debian
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: mvn deploy
